# Generated by Django 3.2.13 on 2023-01-05 01:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lotofacil_app', '0002_auto_20230104_2230'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newgame',
            options={'verbose_name': 'Novo jogo', 'verbose_name_plural': 'Novo jogos'},
        ),
    ]
